### ISSUE TITLE
nfo not working

### ISSUE THREAD

**Issue by MickHere** [slydetector/simply-nzedb#31]
Hi
I have installed simply-nzedb successfully in a vmware image and a intel nuc running Ubuntu server 16.04.1 LTS.
My first problem was the mediainfo path " /usr/local/bin/mediainfo"
for some reason mediainfo was not in that path, I had to install a fresh version then copy mediainfo to that path for it to work.

Second problem I have is that I cant get the nfo to work. When the view nfo button is pressed I get a blank nfo popup. 

I have tested a couple of my usenet service providers to see if they where blocking nfo previews and they work in a newznab vmware I have.

Cheers

**Comment by slydetector** [comment]
I can confirm the NFO issue. Regarding mediainfo, what do you mean when you say "I had to install a fresh version"?

**Comment by MickHere** [comment]
Hi
mediainfo did not work, so I reinstalled it and copied the mediainfo to the /usr/local/bin/ path.

**Comment by slydetector** [comment]
For mediainfo, give this a try and paste the output:
```sh
$ bin/stop_nzedb
$ docker rmi slydetector/simply-nzedb
$ docker pull slydetector/simply-nzedb
$ docker run -it --rm slydetector/simply-nzedb ls -l /usr/local/bin
```

**Comment by MickHere** [comment]
-rwxr-xr-x    1 root     root       9299552 Dec 11 01:55 mediainfo

**Comment by slydetector** [comment]
Well, that proves it is there after forcing a download of the docker image. It is possible an older version of the image may have been flawed, but don't have any other ideas.

**Comment by MickHere** [comment]
Thanks
Its no problem, mediainfo is working atm :)

**Comment by slydetector** [comment]
Ok, tracked down why NFOs are not working. Apparently, iconv under php on alpine is broken: https://forum.alpinelinux.org/forum/installation/php-iconv-issue

So this call https://github.com/nZEDb/nZEDb/blob/d63e1da8967a5cef4fcac8be76db214ffc88fba8/www/pages/nfo.php#L20 returns an empty string instead of the NFO with retro block chars.

May be able to use the LD_PRELOAD workaround here - https://github.com/docker-library/php/issues/240

**Comment by slydetector** [comment]
Fixed in latest build.
